commerce_tax.commerce_tax_type.plugin.usa_tax:
  type: commerce_tax_type_configuration
  mapping:
    display_label:
      type: string
      label: 'Display label'
    round:
      type: boolean
      label: 'Round tax at the order item level'
    rates:
      type: sequence
      label: 'Rates'
      sequence:
        type: mapping
        mapping:
          id:
            type: string
            label: 'ID'
          label:
            type: label
            label: 'Label'
          percentage:
            type: string
            label: 'Percentage'
    territories:
      type: sequence
      label: 'Territories'
      sequence:
        type: address_zone_territory
    product_variation_types:
      type: sequence
      label: 'Product variation types'
      sequence:
        type: string
    commerce_stores:
      type: sequence
      label: 'Store to apply tax to'
      sequence:
        type: string
